// In-memory room store. Nothing is persisted — when a room empties it's deleted
// and all its state is gone.
//
// Identity: players are keyed by a persistent playerId (generated by the client
// and kept in localStorage), NOT by socket.id. The socket is just the current
// wire — it can drop and reconnect (page refresh, network blip) without the
// player losing their seat, host role, or tournament placement.

const rooms = new Map(); // key -> room

// Avoid ambiguous characters (0/O, 1/I) in join keys.
const KEY_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const KEY_LENGTH = 5;

function generateKey() {
  let key;
  do {
    key = "";
    for (let i = 0; i < KEY_LENGTH; i++) {
      key += KEY_ALPHABET[Math.floor(Math.random() * KEY_ALPHABET.length)];
    }
  } while (rooms.has(key));
  return key;
}

const DEFAULT_SETTINGS = { wordCount: 25, wordLang: "en" };

// The creator is always the host, but hosting is independent of racing: an
// organizer may create the room as a spectator and run the tournament
// without playing in it.
export function createRoom(playerId, socketId, name, asSpectator = false) {
  const key = generateKey();
  const member = makePlayer(playerId, socketId, name);
  const room = {
    key,
    hostId: playerId,
    status: "lobby", // lobby | running | finished
    settings: { ...DEFAULT_SETTINGS },
    players: asSpectator ? [] : [member],
    spectators: asSpectator ? [member] : [], // watch-only: never race
    createdAt: Date.now(),
  };
  rooms.set(key, room);
  return room;
}

export function getRoom(key) {
  return rooms.get(key);
}

// Case-insensitive: "Jimmy" and "jimmy" are the same person to everyone else.
function nameTaken(room, name, playerId) {
  const norm = String(name || "").trim().toLowerCase();
  return [...room.players, ...room.spectators].some(
    (m) => m.id !== playerId && m.name.trim().toLowerCase() === norm
  );
}

export function joinRoom(key, playerId, socketId, name) {
  const room = rooms.get(key);
  if (!room) return { error: "Room not found." };
  const existing = room.players.find((p) => p.id === playerId);
  if (existing) {
    // Same person coming back through the join form — treat as reconnect.
    existing.socketId = socketId;
    existing.connected = true;
    return { room };
  }
  if (room.status !== "lobby") return { error: "Tournament already started." };
  if (nameTaken(room, name, playerId))
    return { error: "That name is already taken in this room.", code: "NAME_TAKEN" };
  // One identity, one role: switching to player drops the spectator seat.
  room.spectators = room.spectators.filter((s) => s.id !== playerId);
  room.players.push(makePlayer(playerId, socketId, name));
  return { room };
}

export function joinAsSpectator(key, playerId, socketId, name) {
  const room = rooms.get(key);
  if (!room) return { error: "Room not found." };
  const existing = room.spectators.find((s) => s.id === playerId);
  if (existing) {
    existing.socketId = socketId;
    existing.connected = true;
    return { room };
  }
  if (nameTaken(room, name, playerId))
    return { error: "That name is already taken in this room.", code: "NAME_TAKEN" };

  // One identity, one role. If this person already holds a PLAYER seat
  // (e.g. a second tab in the same browser), being in both lists would let
  // the tournament pull the "spectator" into matches — convert instead.
  const asPlayer = room.players.find((p) => p.id === playerId);
  if (asPlayer) {
    if (room.status !== "lobby")
      return { error: "You are already a player in this room." };
    room.players = room.players.filter((p) => p.id !== playerId);
    // Converting host keeps hosting; hosting is independent of racing.
  }

  // Spectators may join at any time, even mid-tournament.
  room.spectators.push(makePlayer(playerId, socketId, name));
  return { room };
}

export function findRoomByPlayer(playerId) {
  for (const room of rooms.values()) {
    if (room.players.some((p) => p.id === playerId)) return room;
  }
  return null;
}

// Looks through players AND spectators (for chat, reactions, rejoin).
export function findRoomByAnyone(playerId) {
  for (const room of rooms.values()) {
    if (
      room.players.some((p) => p.id === playerId) ||
      room.spectators.some((s) => s.id === playerId)
    )
      return room;
  }
  return null;
}

export function getMember(playerId) {
  const room = findRoomByAnyone(playerId);
  if (!room) return null;
  return (
    room.players.find((p) => p.id === playerId) ??
    room.spectators.find((s) => s.id === playerId) ??
    null
  );
}

export function isSpectator(playerId) {
  const room = findRoomByAnyone(playerId);
  return !!room?.spectators.some((s) => s.id === playerId);
}

export function removeSpectator(playerId) {
  const room = findRoomByAnyone(playerId);
  if (!room) return { room: null, key: null, deleted: false };
  room.spectators = room.spectators.filter((s) => s.id !== playerId);

  if (room.players.length === 0 && room.spectators.length === 0) {
    rooms.delete(room.key);
    return { room: null, key: room.key, deleted: true };
  }
  if (room.hostId === playerId) {
    room.hostId = nextHost(room);
  }
  return { room, key: room.key, deleted: false };
}

export function getPlayer(playerId) {
  const room = findRoomByPlayer(playerId);
  return room?.players.find((p) => p.id === playerId) ?? null;
}

export function isConnected(playerId) {
  return !!getPlayer(playerId)?.connected;
}

// Socket dropped — keep the seat (player OR spectator), mark the wire down.
// Actual removal happens only after the grace period (handled by the caller)
// or an explicit leave.
export function markDisconnected(playerId) {
  const room = findRoomByAnyone(playerId);
  const p =
    room?.players.find((x) => x.id === playerId) ??
    room?.spectators.find((x) => x.id === playerId);
  if (p) {
    p.connected = false;
    p.socketId = null;
  }
  return room;
}

export function reconnectPlayer(playerId, socketId) {
  const room = findRoomByAnyone(playerId);
  const p =
    room?.players.find((x) => x.id === playerId) ??
    room?.spectators.find((x) => x.id === playerId);
  if (!p) return null;
  p.connected = true;
  p.socketId = socketId;
  return room;
}

// Permanently remove a player. Reassigns host if needed and deletes the room
// when nobody (player or spectator) is left.
export function removePlayer(playerId) {
  const room = findRoomByPlayer(playerId);
  if (!room) return { room: null, key: null, deleted: false };

  room.players = room.players.filter((p) => p.id !== playerId);

  if (room.players.length === 0 && room.spectators.length === 0) {
    rooms.delete(room.key);
    return { room: null, key: room.key, deleted: true };
  }
  if (room.hostId === playerId) {
    room.hostId = nextHost(room);
  }
  return { room, key: room.key, deleted: false };
}

// Prefer a connected player, then any player, then a spectator (an
// organizer-only room stays hostable).
function nextHost(room) {
  const candidates = [...room.players, ...room.spectators];
  const next = candidates.find((m) => m.connected) ?? candidates[0];
  return next?.id ?? null;
}

export function updateSettings(room, partial) {
  const s = room.settings;
  if ([15, 25, 50].includes(partial?.wordCount)) s.wordCount = partial.wordCount;
  if (["en", "uz"].includes(partial?.wordLang)) s.wordLang = partial.wordLang;
}

function makePlayer(id, socketId, name) {
  return {
    id,
    socketId,
    name: (name || "Anon").slice(0, 16),
    connected: true,
  };
}

// Public, serializable view of a room for the lobby UI.
export function publicRoom(room) {
  return {
    key: room.key,
    hostId: room.hostId,
    status: room.status,
    settings: room.settings,
    players: room.players.map((p) => ({
      id: p.id,
      name: p.name,
      connected: p.connected,
    })),
    spectators: room.spectators.map((s) => ({
      id: s.id,
      name: s.name,
      connected: s.connected,
    })),
  };
}
