// In-memory room store. Nothing is persisted — when a room empties it's deleted
// and all its state is gone.
//
// Identity: players are keyed by a persistent playerId (generated by the client
// and kept in localStorage), NOT by socket.id. The socket is just the current
// wire — it can drop and reconnect (page refresh, network blip) without the
// player losing their seat, host role, or tournament placement.

const rooms = new Map(); // key -> room

// Avoid ambiguous characters (0/O, 1/I) in join keys.
const KEY_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const KEY_LENGTH = 5;

function generateKey() {
  let key;
  do {
    key = "";
    for (let i = 0; i < KEY_LENGTH; i++) {
      key += KEY_ALPHABET[Math.floor(Math.random() * KEY_ALPHABET.length)];
    }
  } while (rooms.has(key));
  return key;
}

const DEFAULT_SETTINGS = { wordCount: 25, wordLang: "en" };

export function createRoom(playerId, socketId, name) {
  const key = generateKey();
  const room = {
    key,
    hostId: playerId,
    status: "lobby", // lobby | running | finished
    settings: { ...DEFAULT_SETTINGS },
    players: [makePlayer(playerId, socketId, name)],
    createdAt: Date.now(),
  };
  rooms.set(key, room);
  return room;
}

export function getRoom(key) {
  return rooms.get(key);
}

export function joinRoom(key, playerId, socketId, name) {
  const room = rooms.get(key);
  if (!room) return { error: "Room not found." };
  const existing = room.players.find((p) => p.id === playerId);
  if (existing) {
    // Same person coming back through the join form — treat as reconnect.
    existing.socketId = socketId;
    existing.connected = true;
    return { room };
  }
  if (room.status !== "lobby") return { error: "Tournament already started." };
  room.players.push(makePlayer(playerId, socketId, name));
  return { room };
}

export function findRoomByPlayer(playerId) {
  for (const room of rooms.values()) {
    if (room.players.some((p) => p.id === playerId)) return room;
  }
  return null;
}

export function getPlayer(playerId) {
  const room = findRoomByPlayer(playerId);
  return room?.players.find((p) => p.id === playerId) ?? null;
}

export function isConnected(playerId) {
  return !!getPlayer(playerId)?.connected;
}

// Socket dropped — keep the seat, mark the wire down. Actual removal happens
// only after the grace period (handled by the caller) or an explicit leave.
export function markDisconnected(playerId) {
  const room = findRoomByPlayer(playerId);
  const p = room?.players.find((x) => x.id === playerId);
  if (p) {
    p.connected = false;
    p.socketId = null;
  }
  return room;
}

export function reconnectPlayer(playerId, socketId) {
  const room = findRoomByPlayer(playerId);
  const p = room?.players.find((x) => x.id === playerId);
  if (!p) return null;
  p.connected = true;
  p.socketId = socketId;
  return room;
}

// Permanently remove a player. Reassigns host if needed and deletes the room
// when no one is left.
export function removePlayer(playerId) {
  const room = findRoomByPlayer(playerId);
  if (!room) return { room: null, key: null, deleted: false };

  room.players = room.players.filter((p) => p.id !== playerId);

  if (room.players.length === 0) {
    rooms.delete(room.key);
    return { room: null, key: room.key, deleted: true };
  }
  if (room.hostId === playerId) {
    const next = room.players.find((p) => p.connected) ?? room.players[0];
    room.hostId = next.id;
  }
  return { room, key: room.key, deleted: false };
}

export function updateSettings(room, partial) {
  const s = room.settings;
  if ([15, 25, 50].includes(partial?.wordCount)) s.wordCount = partial.wordCount;
  if (["en", "uz"].includes(partial?.wordLang)) s.wordLang = partial.wordLang;
}

function makePlayer(id, socketId, name) {
  return {
    id,
    socketId,
    name: (name || "Anon").slice(0, 16),
    connected: true,
  };
}

// Public, serializable view of a room for the lobby UI.
export function publicRoom(room) {
  return {
    key: room.key,
    hostId: room.hostId,
    status: room.status,
    settings: room.settings,
    players: room.players.map((p) => ({
      id: p.id,
      name: p.name,
      connected: p.connected,
    })),
  };
}
